### ISSUE TITLE
Error is Blank

### ISSUE THREAD

**Issue by intrepidws** [aryehraber/statamic-recaptcha#1]
The error array seems to have an entry for a reCAPTCHA that is left blank - but the error itself is empty. There is no text for it. The code below shows how I am trying to retrieve the errors:

```
{{ form:set is="contact-us" }}
    {{ if {form:errors} }}
    <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p><strong>Uh Oh!</strong> We need some more information from you.</p>
        {{ form:errors | ampersand_list }}
    </div>
    {{ /if }}
{{ /form:set }}
```

**Comment by intrepidws** [comment]
Forget it - I had used my .env file to add my key information, so I didn't know that there was an error message field. Perhaps it would make sense to provide a default value for that?

**Comment by aryehraber** [comment]
@intrepidws: Thanks for bringing this to my attention! It _should_ default to `reCAPTCHA failed.` but apparently it isn’t… Will have a look into it!

**Comment by aryehraber** [comment]
p.s. the error message can also be handled through the CP Addon Settings (CP > Configure > Addons > Recaptcha).

**Comment by intrepidws** [comment]
Yea, that's where I eventually found it.

Great add-on, thanks for your work.

**Comment by intrepidws** [comment]
I have been doing some testing for a possible solution. It seems that the getConfig() function doesn't really do what it should (at least in my opinion) when a config setting exists but is empty. It will still return the empty setting, rather than using the provided default. So it seems that your best bet for a fix is to provide a default value in the `site/addons/Recaptcha/default.yaml` file. I can make a pull request if you'd like.

**Comment by aryehraber** [comment]
Nice catch, I think that was it! Just updated the `default.yaml` file. Thanks!
