### ISSUE TITLE
Ability for JS callback

### ISSUE THREAD

**Issue by cibgraphics** [aryehraber/statamic-recaptcha#11]
I have a website that is submitting the form via ajax. It would be nice to be able to interact with the captcha via callback.

Docs have it for v2 as a simple data attribute, but I didn't see an option to add this in this plugin

```
data-callback="recaptcha_callback"
```

Is it possible to add this to the plugin or is there another way?

**Comment by aryehraber** [comment]
Hi @cibgraphics! 

I need to update the docs for this, but until then have a look at my previous comment on another issue: https://github.com/aryehraber/statamic-recaptcha/issues/10#issuecomment-488585170

Should probably add the ability for custom attributes to make this simpler, but hopefully the above works for you for now.

**Comment by cibgraphics** [comment]
Maybe I misunderstanding something. To render the captcha, I need to do an explicit render which I can do just fine. I can get a response via javascript which gives me a token. But without the use of the plugin (because I am using explicit rendering), I can no longer use the plugin to actually send it to Google for verification.

Am I missing something?

**Comment by aryehraber** [comment]
The Addon is exclusively built for Statamic's Forms, so assuming that's what you're using this for I don't think you're missing anything 😊 

When the Recaptcha Addon is installed, and you've configured which forms you'd like it to secure (via `CP > Configure > Addons > Recaptcha`), anytime that form is submitted it will do the Recaptcha check for you (take the frontend token and verify via their API). If this token is missing or fails, the form returns an error, just like Statamic would normally throw an error if a required field is missing, for example.

**Comment by aryehraber** [comment]
I'm closing this issue because it has been inactive for some time. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://statamic.com/marketplace/addons/google-recaptcha). You can also contribute directly by providing a PR.

Thank you!
