### ISSUE TITLE
Port to Statamic V3?

### ISSUE THREAD

**Issue by twd3** [aryehraber/statamic-recaptcha#13]
Will you be porting this to work with Statamic V3? That would be very nice. I'll donate...

**Comment by aryehraber** [comment]
Hi @twd3! I would definitely like to upgrade this addon to Statamic V3 but haven't had the chance yet. Last time I had a look at V3 they didn't have Forms support yet, though this was a little while ago now so hopefully this has changed. 

Will keep you posted here when the time comes!

**Comment by aryehraber** [comment]
@twd3 Just released the Statamic 3 upgrade as a beta, available via this dev branch:
https://github.com/aryehraber/statamic-recaptcha/tree/statamic-3

The README has been updated with new installation instructions, let me know if you have any issues!

**Comment by twd3** [comment]
Best news I've heard in a while. Thank you very much. I'll install and test out tomorrow. Love your avatar haha! I doubt you need it but I'd like to donate for this. I checked out your site to try and find a way to donate but couldn't find anything.

**Comment by aryehraber** [comment]
Thanks @twd3, very much appreciate the gesture! Been thinking about setting up GitHub Sponsors to try and make my work more sustainable... will let you know if/when I set this up in case you're still interested in supporting my open-source work by then 😊 

Back to the addon: let me know how the install goes and whether anything is unclear or doesn't work!

**Comment by twd3** [comment]
Yeah let me know, I'd love to donate. The install went perfectly and I have it working in dev.

**Comment by aryehraber** [comment]
@twd3 Awesome, appreciate it very much and will let you know when I've set something up 👍 

Thanks for testing it out, will close the issue now!

**Comment by aryehraber** [comment]
@twd3 Just wanted to let you know that my GitHub Sponsor page was accepted over the weekend. So if you're still interested in donating and supporting future dev of this addon (and others!), a sponsorship would be much appreciated!
