### ISSUE TITLE
Getting errors, unhandled promise timeout

### ISSUE THREAD

**Issue by edalzell** [aryehraber/statamic-recaptcha#17]
Looks like this [issue](https://github.com/google/recaptcha/issues/269)?

@aryehraber have you tried this recently?

This error is occurring when I hit the submit button on my form.

I have added head stuff, and the `{{ recaptcha }}` tag, everything is appearing in my page. I have added my test domain to my account on Google and put the two keys in `.env`.

Any ideas on how to troubleshoot?

**Comment by aryehraber** [comment]
First I'm hearing of this. We use this addon on all our sites and haven't seen/noticed this issue before. 

You getting it on a staging/production server too, or just locally? 

To check whether things are working as expected, are you seeing Google/Recaptcha related activity in Network tab?

**Comment by edalzell** [comment]
I was trying to use v3 recaptcha
