### ISSUE TITLE
Possible to specify language for recaptcha?

### ISSUE THREAD

**Issue by bertheyman** [aryehraber/statamic-recaptcha#26]
Hi, thanks for building this plugin!

Is it possible to specify the language for recaptcha when using the render tag?
For now, I've bypassed this by including the link myself and appending with `?hl=language_shortcode` - would prefer to use the tag provided by your package.

**Comment by aryehraber** [comment]
Good idea, will look into adding this feature 👍

**Comment by aryehraber** [comment]
Added support for languages in latest release 🎉 

https://statamic.com/marketplace/addons/google-recaptcha

Once upgraded, you'll see the new option in Recaptcha's settings. 

Let me know if you run into any issues!

**Comment by bertheyman** [comment]
Great, thanks!
