### ISSUE TITLE
Two Forms on One Page Issues

### ISSUE THREAD

**Issue by twd3** [aryehraber/statamic-recaptcha#29]
Has this been tested with two forms on one page? I am having issues with allowing two forms on one page. All handles are unique. I can't figure it out. Was wondering if you had tested?

**Comment by aryehraber** [comment]
As far as I know this should work, but I can run a test on my end when I have time to double check (been a while). 

Which Recaptcha setup are you using?

**Comment by twd3** [comment]
Using V2 invisible. I have it live if you want to test live, I'm the only one getting these form submissions.

**Comment by delz-dev** [comment]
Same Problem here … 2 forms on same page: Unique ID's but second form (lower on the page) is not working.

**Comment by aryehraber** [comment]
Hey @delz-dev, just to double check... are you using Statamic V2?

**Comment by delz-dev** [comment]
Yep, V2

Am Di., 29. Sept. 2020 um 16:32 Uhr schrieb Aryeh Raber <
notifications@github.com>:

**Comment by aryehraber** [comment]
@delz-dev Ok cool, thanks for confirming! Just noticed that I only fixed this issue in the V3 branch and new Captcha addon. Will fix this week!

**Comment by delz-dev** [comment]
Nice, thank you!

Am Di., 29. Sept. 2020 um 16:52 Uhr schrieb Aryeh Raber <
notifications@github.com>:
