### ISSUE TITLE
High amount of spam coming through

### ISSUE THREAD

**Issue by aryehraber** [aryehraber/statamic-recaptcha#30]
Well, the only thing is I really don't think V2 is working anymore. I think the bots figured it out. I've had the V2 (for Statamic V3) installed and live for a week now and the spam is coming through like crazy. On Wednesday I turned the "security" up all the way. Just last night I got 0 leads and 20 spams. It is so bad I cannot let the executives get the email notifications right now because it would make me look so bad as their developer so I have to look for actual leads right now and then forward them out. It's bad because they really need to respond to these leads right away and this makes a lag.

I guess I don't understand why honeypot and this V2 solution doesn't work for me. All leads you see in following screenshot was spam leads from last night.

_Originally posted by @twd3 in https://github.com/aryehraber/statamic-recaptcha/issues/5#issuecomment-657097047_

**Comment by aryehraber** [comment]
Hey @twd3, starting a new issue since this is unrelated to the V3 request.

Reading your comment definitely doesn't sound like a great situation! I've personally not encountered that much spam on client sites once I turned Recaptcha's security setting all the way up (on lower settings I have had issues). 

Can you confirm that Recaptcha is setup correctly within Statamic? By default, it doesn't actually stop form submissions, you must opt-in to which forms you'd like to protect (see step 3 in Setup section: https://github.com/aryehraber/statamic-recaptcha#setup). 

Assuming the above is setup correctly I'm not really sure what to suggest other than getting in touch with Recaptcha's support. Alternatively you can try switch to hCaptcha since bots probably aren't trained as well to solve those challenges (see [docs here](https://github.com/aryehraber/statamic-recaptcha#hcaptcha)). As a last resort, you can try out the [Akismet addon](https://statamic.com/addons/silentz/akismet) to better handle spam within Statamic. 

For what it's worth, I've implemented Recaptcha V3 on client sites in the past and spam skyrocketed, even after several weeks it would still let tens of spam submissions through per day, while blocking real customer submission (humans) which ended up as a huge problem after which we reverted back to Recaptcha V2 which has continued to work great since.

**Comment by twd3** [comment]
Thanks for this response! Yeah, I think you're right...reCAPTCHA V3 may be a waste of time. I did put the forms in the config like:
'forms' => ['quick_contact', 'quick_contact_sm', 'contact', 'submit-testimonial', 'employment'],
So I really don't know what is happening. I have this live if you want to check it out DM me on discord or something. I may be trying h-captcha today...thanks again!

**Comment by twd3** [comment]
Now I think there is a mis-configuration. I just got this message at the reCAPTCHA dashboard this morning.


Any help would be greatly appreciated, willing to pay for time.

**Comment by aryehraber** [comment]
Ah ok this is on Statamic 3? I didn't quite follow that part, I haven't personally used this in production yet so perhaps you've come across a bug. Did you ever have similar issues (bots getting through on high security) on Statamic 2 site?

I'll try and pop you a message on Discord after work!

**Comment by twd3** [comment]
Yes, live Statamic 3 (I'm brave like that :-)  No, I think the V2 sites I've used your solution on are working great.

**Comment by aryehraber** [comment]
@twd3 Just pushed some changes which should hopefully fix the issue. It was related to the Statamic Beta 37 which changed how addons should listen and intercept form submission events.

Let me know if this fixes it for you! 

Easiest way to test: 

- Before updating addon, switch to regular Recaptcha (where you have to manually tick the checkbox)
- Fill in your form **without** ticking Recaptcha checkbox
- The form should submit successfully even though Recaptcha wasn't used
- Now update the addon (`composer update aryehraber/statamic-recaptcha`)
- Fill in your form **without** ticking Recaptcha checkbox
- The form should submit and return a Recaptcha error

p.s. also worth noting I had to update my Form template based on the new example in the docs to get error messages to show correctly (not sure when this changed, you may already have this setup correctly): https://statamic.dev/forms#your-first-form

**Comment by twd3** [comment]
Thanks a ton for jumping on this!

When invisible set to false (checkbox) you have to click submit twice. Once to get recaptcha images, you solve, then you have to hit submit again and it comes through.

It doesn't continue submitting the form after you select the right recaptcha images when invisible used no matter how many times you hit submit button, more recaptcha images just keep appearing. I'm sure same issue.

**Comment by aryehraber** [comment]
Ok thanks for testing. The checkbox Recaptcha was working fine for me; after ticking box and solving challenge I was able to click Submit just once. I didn't get round to testing Invisible but sounds like I may need to have a closer look.

**Comment by twd3** [comment]
I even tried my form:create wrapped in form:set.

If you said the tick box worked for you last night I'll test again. Thanks again.

**Comment by twd3** [comment]
Just tested the checkbox version again to be sure and yes, I had to click submit once to do captcha then it stops and I had to submit again but then the form did submit. Did the form you tested on have simple validation like required? Also, just so you know I don't use the {{ if success }} on the forms because I redirect to thank you pages. Don't know if that matters. Here are examples of the form templates: https://github.com/statamic/cms/issues/2072

**Comment by aryehraber** [comment]
@twd3 I think I cracked it, would love if you could test and verify that everything now works as expected; 1) spam count goes back down, 2) multiple forms on single page work correctly.

`composer update aryehraber/statamic-recaptcha` should pull in latest version.

Thanks!

**Comment by twd3** [comment]
It's not working locally so I haven't pushed the changes to the server. I fill the recaptcha and it never continues submitting the form even if I hit submit again. You were really close last night because I only got one spam today and I verified the forms are working. So you were close and that two form thing could just be Statamic beta issue...

**Comment by aryehraber** [comment]
@twd3 Hmm, since it seems to be working on my end in a demo project, as well as my local version of your project, would you mind reinstalling the package just to make sure it's using the right version?

First run: `composer remove aryehraber/statamic-recaptcha`

Then run: `composer require aryehraber/statamic-recaptcha:dev-statamic-3`

Thanks!

**Comment by twd3** [comment]
Will do right when I get in to the office.

**Comment by twd3** [comment]
Working on local for one form. Getting that same 500 error on that small form. This may be a Statamic thing though...I got and solved the captcha on the small form but when it went to then submit got that 500. You think I should make this version live though because that smaller form is not really live and this version is more up-to-date?

**Comment by twd3** [comment]
This is awesome, thanks again!!! You can close this if you want.
