### ISSUE TITLE
Statamic V3 Beta 38 Breaking Change for Events Folder Move is Breaking the Latest Version of statamic-recaptcha for V-3

### ISSUE THREAD

**Issue by twd3** [aryehraber/statamic-recaptcha#31]
Statamic V3 Beta 38 included a breaking change where the Events Folder moved. This must be breaking the latest version of statamic-recaptcha for V-3.

See last bullet point here:
https://github.com/statamic/cms/releases/tag/v3.0.0-beta.38
And this maybe?
https://github.com/statamic/cms/commit/c2c15f08813d66d5144c893c443f271ab3c636d3

**Comment by aryehraber** [comment]
This has now been fixed!

Please update to latest version if you are running Statamic Beta 38+: `composer update aryehraber/statamic-recaptcha`

If above doesn't work, please remove the addon and reinstall:

First run: `composer remove aryehraber/statamic-recaptcha`

Then run: `composer require aryehraber/statamic-recaptcha:dev-statamic-3`
