### ISSUE TITLE
Main-thread blocking

### ISSUE THREAD

**Issue by jeremydouglas** [aryehraber/statamic-recaptcha#33]
Not sure if this is an issue with the add-on or just something I need to dig deeper on with Recaptcha in general. 

I'm running Statamic 3 with recaptcha V2 invisible. 

This is what's showing up in Google Pagespeed:

<img width="750" alt="google-pagespeed-report" src="https://user-images.githubusercontent.com/113216/90822306-37925c80-e302-11ea-8add-730ab6cd2be4.png">

Anyhow, not sure if it's something that can be changed in the add-on, but this is my next step in fixing it.

**Comment by aryehraber** [comment]
Hey @jeremydouglas, unfortunately I don't think this is something this addon can help with. The `head` tag simply outputs reCAPTCHA's script as per their docs, which already defers loading: 

```js
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
```

If you have any suggestions feel free to reopen this issue or submit a PR!
