### ISSUE TITLE
Looks like another update...FormSubmitted event gets a submission property...

### ISSUE THREAD

**Issue by twd3** [aryehraber/statamic-recaptcha#34]
Just a heads up for this 3.0.1 update. This: "The FormSubmitted event gets a submission property. #2271" was fixed so you may have to update. I think it's about time for me to go back to using this after this next update.

**Comment by aryehraber** [comment]
@twd3 Thanks for the heads up, I was already part of the original GH issue https://github.com/statamic/cms/issues/2271 😉 

Btw, this repo has been abandoned and I've started a fresh addon with a (slightly) new name:
https://github.com/aryehraber/statamic-captcha -- works the same as before, but let me know (in that repo) if you have any issues!
