### ISSUE TITLE
reCAPTCHA bypasses form validation

### ISSUE THREAD

**Issue by jsbls** [aryehraber/statamic-recaptcha#8]
Whenever the user adds input validation to the form (whether such form is sent via AJAX or the regular Statamic action), reCAPTCHA still submits the form, even if the form has errors or conditionals (i.e. empty required input, or preventDefault).

Not sure if it changes anything but I'm using Invisible reCAPTCHA.

Here's a quick example using Bootstrap's client-side validation (which gets overridden by reCAPTCHA)

```
form.addEventListener('submit', function(event) {
  if (form.checkValidity() === false) {
    event.preventDefault()
    event.stopPropagation()
  }
  
  form.classList.add('was-validated')

}, false)
```

Any help would be greatly appreciated!

**Comment by aryehraber** [comment]
Sounds like something isn't quite right here; Recaptcha doesn't "submit" the form, Statamic handles this. In fact Recaptcha doesn't even get touched until Statamic's own validation rules have passed, if any form validation errors are found (eg: required name is blank) then Statamic returns the errors to the frontend without having informed Recaptcha, or any other form listening addons, of the form submission.

It's hard to tell what exactly is going wrong in your use case, but I'd recommend you strip everything down without using Ajax and get it to work as expected like that first.

**Comment by jsbls** [comment]
I know it's super weird. The problem doesn't appear to be limited to AJAX forms though, I tried adding`{{ recaptcha }}` to a regular formset and it still skips client-side validation. (I think the main problem is with actions that occur before Statamic's server-side validation, ie. HTML5's CheckValidity). 

The weird thing is, if I remove recaptcha, I can preventDefault, but that same code doesn't work with recaptcha on. A quick example would just be:

```
form.submit(function(event) {
  if (form.checkValidity() === false) {
    event.preventDefault()
  }
}
```

I'll definitely try to strip a form and see if I can get it going, or at least get a screen recording of an actual form displaying the error. (Sorry for the super convoluted explanation too! :) )

Thanks for your answer!

*EDIT:* Indeed, the problem appears to be exclusively with forms that use client-side validation.

**Comment by aryehraber** [comment]
I'm closing this issue because it has been inactive for some time. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://statamic.com/marketplace/addons/google-recaptcha). You can also contribute directly by providing a PR.

Thank you!
